config/routes.rb
Reddundancy::Application.routes.draw do
  root to: "static_pages#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

#   Rails UI is deprecated.  All user interface should be through Backbone.
#
#   resources :users, only: [:show]
#
#   This route will redirect to the appropriate Backbone view.
  resources :sub_reddits, only: [:show, :index], path: "s"
#     resources :posts, only: [:new, :create]
#   end
#   resources :posts, only: [:show] do
#     resources :comments, only: [:new, :create]
#   end
#   resources :comments, only: [:show] do
#     resources :comments, only: [:new, :create]
#   end
#
#   resources :votes, only: [:create, :update]

  namespace :api, :defaults => { :format => :json } do
    resources :sub_reddits, only: [:index, :show, :create, :update, :destroy],
    path: "s" do
      resources :posts, only: [:index]
      resource :user_subs, only: [:create, :update, :destroy], path: "favorite"
    end
    resources :posts, only: [:show, :create, :update, :destroy] do
      resources :comments, only: [:index, :create]
    end
    resources :comments, only: [:show, :create, :update, :destroy] do
      resources :comments, only: [:create]
    end
    resources :users, only: [] do
      resources :user_subs, only: [:index], path: "favorites"
    end

    resources :votes, only: [:create, :update, :destroy]
  end
end

app/views/navbar/_navbar_header.html.erb
<button type="button" class="navbar-toggle" data-toggle="collapse"
  data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="#">Reddundancy</a>
<!-- end navbar header -->

app/views/navbar/_signed_in_navbar_els.html.erb
<ul class="nav navbar-nav navbar-left">
  <li class="dropdown">
    <button class="btn dropdown-toggle" type="button"
      id="favorited-subs-dropdown-btn" data-toggle="dropdown">
      Your Favorite Subs
      <span class="caret"></span>
    </button>

    <ul id="favorited-subs" class="dropdown-menu ui-sortable"
      aria-labelledby="favorited-subs-dropdown-btn">
      <!-- Backbone will populate favorited-subs contents -->
    </ul>
  </li>
  <li>
    <p class="navbar-text"><em>Drag/drop your favorites to reorder!</em></p>
  </li>
</ul>

<ul class="nav navbar-nav navbar-right">
  <li>
    <div id="loading-icon" class="hidden"></div>
  </li>
  <li>
    <p class="navbar-text">Welcome, <%= current_user.username %>!</p>
  </li>
  <li>
    <%= button_to "Sign Out", session_url, method: :delete,
    class: "btn navbar-btn btn-danger"%>
  </li>
</ul>
<!-- end navbar body -->

app/views/navbar/_signed_out_navbar_els.html.erb
<ul class="nav navbar-nav navbar-left">
</ul>

<ul class="nav navbar-nav navbar-right">
  <li>
    <div id="loading-icon" class="hidden"></div>
  </li>
  <li><p class="navbar-text">Not signed in.</p></li>

  <li><a href="<%= new_session_url %>" id="nav-signin-link"
    class="btn navbar-btn btn-success nav-link-btn">Sign In</a>
  </li>

  <li><a href="<%= new_user_url%>" id="nav-signup-link"
    class="btn navbar-btn btn-primary nav-link-btn">Sign Up</a>
  </li>
</ul>
<!-- end navbar body -->