config/routes.rb
Reddundancy::Application.routes.draw do
  root to: "static_pages#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

#   Rails UI is deprecated.  All user interface should be through Backbone.
#
#   resources :users, only: [:show]
#
#   This route will redirect to the appropriate Backbone view.
  resources :sub_reddits, only: [:show, :index], path: "s"
#     resources :posts, only: [:new, :create]
#   end
#   resources :posts, only: [:show] do
#     resources :comments, only: [:new, :create]
#   end
#   resources :comments, only: [:show] do
#     resources :comments, only: [:new, :create]
#   end
#
#   resources :votes, only: [:create, :update]

  namespace :api, :defaults => { :format => :json } do
    resources :sub_reddits, only: [:index, :show, :create, :update, :destroy],
    path: "s" do
      resources :posts, only: [:index]
      resource :user_subs, only: [:create, :update, :destroy], path: "favorite"
    end
    resources :posts, only: [:show, :create, :update, :destroy] do
      resources :comments, only: [:index, :create]
    end
    resources :comments, only: [:show, :create, :update, :destroy] do
      resources :comments, only: [:create]
    end
    resources :users, only: [] do
      resources :user_subs, only: [:index], path: "favorites"
    end

    resources :votes, only: [:create, :update, :destroy]
  end
end

app/views/votable/_karma.html.erb
<p>This UI has been deprecated.  Please visit <a href="">the new homepage.</a></p>

<div class="karma">
  <% if model.user_already_voted?(current_user) %>
  <form action="<%= vote_url %>" method="POST">
    <input type="hidden" name="_method" value="PUT"></input>
    <input type="hidden" name="vote[up]" value="true"></input>
    <%= render "votable/vote_hidden_fields", model: model %>
    <input type="submit" value="Upboat!"
      class="upvote <%= model.user_upvoted?(current_user) ?
      'active' : '' %>"></input>
  </form>
  Karma: <%= model.karma %>
  <form action="<%= vote_url %>" method="POST">
    <input type="hidden" name="_method" value="PUT"></input>
    <input type="hidden" name="vote[up]" value="false"></input>
    <%= render "votable/vote_hidden_fields", model: model %>
    <input type="submit" value="Downboat!"
      class="downvote <%= model.user_upvoted?(current_user) ?
      '' : 'active' %>"></input>
  </form>

  <% else %>

  <form action="<%= vote_url %>" method="POST">
    <input type="hidden" name="vote[up]" value="true"></input>
    <%= render "votable/vote_hidden_fields", model: model %>
    <input type="submit" value="Upboat!" class="upvote"></input>
  </form>
  Karma: <%= model.karma %>
  <form action="<%= vote_url %>" method="POST">
    <input type="hidden" name="vote[up]" value="false"></input>
    <%= render "votable/vote_hidden_fields", model: model %>
    <input type="submit" value="Downboat!" class="downvote"></input>
  </form>
  <% end %>
</div>

app/views/votable/_vote_hidden_fields.html.erb
<p>This UI has been deprecated.  Please visit <a href="">the new homepage.</a></p>

<%= csrf_token %>
<input type="hidden" name="vote[votable_id]" value="<%= model.id %>"></input>
<input type="hidden" name="vote[votable_type]"
  value="<%= model.class.name %>"></input>