config/routes.rb
Reddundancy::Application.routes.draw do
  root to: "static_pages#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

#   Rails UI is deprecated.  All user interface should be through Backbone.
#
#   resources :users, only: [:show]
#
#   This route will redirect to the appropriate Backbone view.
  resources :sub_reddits, only: [:show, :index], path: "s"
#     resources :posts, only: [:new, :create]
#   end
#   resources :posts, only: [:show] do
#     resources :comments, only: [:new, :create]
#   end
#   resources :comments, only: [:show] do
#     resources :comments, only: [:new, :create]
#   end
#
#   resources :votes, only: [:create, :update]

  namespace :api, :defaults => { :format => :json } do
    resources :sub_reddits, only: [:index, :show, :create, :update, :destroy],
    path: "s" do
      resources :posts, only: [:index]
      resource :user_subs, only: [:create, :update, :destroy], path: "favorite"
    end
    resources :posts, only: [:show, :create, :update, :destroy] do
      resources :comments, only: [:index, :create]
    end
    resources :comments, only: [:show, :create, :update, :destroy] do
      resources :comments, only: [:create]
    end
    resources :users, only: [] do
      resources :user_subs, only: [:index], path: "favorites"
    end

    resources :votes, only: [:create, :update, :destroy]
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  link       :string(255)
#  owner_id   :integer          not null
#  sub_id     :integer
#  created_at :datetime
#  updated_at :datetime
#  title      :string(255)      not null
#

class Post < ActiveRecord::Base
  include Votable
  include Commentable
  validates :owner, :sub, :title, presence: true

  belongs_to :sub,
    class_name: "SubReddit",
    foreign_key: :sub_id,
    inverse_of: :posts
  belongs_to :owner, class_name: "User", inverse_of: :owned_posts
  has_many :comments, inverse_of: :post, dependent: :destroy
  has_many :votes, as: :votable, inverse_of: :votable, dependent: :destroy
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :ensure_signed_in, only: [:update, :destroy, :create]
  before_action :verify_ownership, only: [:update, :destroy]

  def index
    #extra SQL query, but allows use of friendlyID
    @sub = SubReddit.friendly.find(params[:sub_reddit_id].to_s.downcase)
    @posts = Post.includes(:sub, :owner, :comments, :votes => :owner)
                 .where(sub_id: @sub.id)
                 .order(:created_at => :desc)
                 .page(params[:page])
                 .per(10)
    render :index, locals: {posts: @posts}
  end

  def show
    #Note: Comments sent as a flat structure
    #All entries in the comment tree (top-level comments and subcomments)
    #will be included, but the JSON structure does not reflect the tree structure
    @post = Post.includes(:sub, :owner, { :votes => :owner }, comments:
      [:votes, :comments, :owner]).find(params[:id])
    render :show, locals: {post: @post}
  end

  def create
    @post = SubReddit.find(post_params[:sub_id]).posts.build(post_params)
    @post.owner_id = current_user.id
    if @post.save
      render :show, locals: {post: @post}
    else
      render :json => @post.errors.full_messages, status: 422
    end
  end

  def update
    #@post found in verify_ownership
    if @post.update_attributes(post_params)
      render :show, locals: {post: @post}
    else
      render :json => @post.errors.full_messages, status: 422
    end
  end

  def destroy
    #@post found in verify_ownership
    if @post
      @post.destroy
      render :show, locals: {post: @post}
    else
      head 404
    end
  end

  private
  def post_params
    params.require(:post).permit(:link, :title, :body, :sub_id)
  end

  def verify_ownership
    @post = Post.includes(:owner).find(params[:id])
    head 403 unless @post.owner == current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Rails UI is deprecated.  All content UI should be through Backbone.

  before_action :ensure_signed_in, only: [:new, :create]
#   def index
#   end

  def new
    @post = SubReddit.find(params[:sub_reddit_id]).posts.build
    render :new, locals: {post: @post}
  end

  def create
    @post = SubReddit.find(params[:sub_reddit_id]).posts.build(post_params)
    @post.owner_id = current_user.id
    if @post.save
      flash[:notice] = "Post successfully created!"
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new, locals: {post: @post}
    end
  end

  def show
    @post = Post.includes(:votes, :sub, :owner).find(params[:id])
    #comments not in includes due to load/sort function in next line
    @post_comments_by_parent_id = Comment.post_comments_by_parent_id(@post.id)
    render :show, locals: {post: @post,
      post_comments_by_parent_id: @post_comments_by_parent_id}
  end

#   def edit
#   end
#
#   def update
#   end
#
#   def destroy
#   end

  private
  def post_params
    params.require(:post).permit(:link, :title)
  end
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  # Rails UI is deprecated.  All content UI should be through Backbone.
end

app/views/posts/_comment.html.erb
<p>This UI has been deprecated.  Please visit <a href="">the new homepage.</a></p>

<div id="comment-<%= comment.id %>">
  <%= comment.owner.username %> wrote:
  <%= comment.body %>

  <ul><% post_comments_by_parent_id[comment.id].each do |subcomment| %>
    <li><%= render "comment", comment: subcomment,
      post_comments_by_parent_id: post_comments_by_parent_id %></li>
  <% end %></ul>
</div>

app/views/posts/_form.html.erb
<p>This UI has been deprecated.  Please visit <a href="">the new homepage.</a></p>

<h2>Create a Post</h1>
<h3>Sub: <%= post.sub.name %></h3>

<div class="form-container">
  <form action="<%= sub_reddit_posts_url(sub) %>" method="POST">
    <%= csrf_token %>

    <div class="form-group">
      <label>Title:
      <input type="text"
        name="post[title]"
        class="form-control"
        value="<%= post.title %>"
        placeholder="Title"></input>
      </label>
    </div>

    <div class="form-group">
      <label>URL:
      <input type="text"
        name="post[link]"
        class="form-control"
        placeholder="URL"></input>
      </label>
    </div>

    <input type="submit" class="btn btn-success" value="Create Post!"></input>
  </form>
</div>

app/views/posts/new.html.erb
<p>This UI has been deprecated.  Please visit <a href="">the new homepage.</a></p>

<%= render "form", post: post, sub: post.sub %>

app/views/posts/show.html.erb
<p>This UI has been deprecated.  Please visit <a href="">the new homepage.</a></p>

<%= puts post.link %>
<% if post.link.nil? %>
  <h1><%= post.title %></h1>
<% else %>
  <h1><a href="http://<%= post.link %>"><%= post.title %></a></h1>
<% end %>

<% post_comments_by_parent_id["toplevel"].each do |comment| %>
  <%= render "comment", comment: comment,
     post_comments_by_parent_id: post_comments_by_parent_id %>
<% end %>

<%= render "comments/form", post: post, comment: post.comments.build %>